=== joomla-x/joomla-pythagoras/libraries/incubator/ORM/Definition/entity.dtd
<!ELEMENT entity ((storage)?, fields, (relations)?)>
    <!ATTLIST entity
        name CDATA #REQUIRED
        role (primary|lookup|map|inline|default) "default">

    <!ELEMENT storage (default|csv|api|special)>

    <!ELEMENT default EMPTY>
    <!ATTLIST default
        table NMTOKEN #REQUIRED>

    <!ELEMENT api EMPTY>
    <!ATTLIST api
        base-url CDATA #IMPLIED
        handler CDATA #REQUIRED>

    <!ELEMENT csv EMPTY>
    <!ATTLIST csv
        file CDATA #REQUIRED>

    <!ELEMENT special EMPTY>
    <!ATTLIST special
        dsn CDATA #REQUIRED>

    <!ELEMENT fields (field|fieldset)+>

    <!ELEMENT fieldset (field+|case+)>
    <!ATTLIST fieldset
        name ID #REQUIRED
        type NMTOKEN #REQUIRED
        entity CDATA #IMPLIED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT field (validation|option)*>
    <!ATTLIST field
        name ID #REQUIRED
        type NMTOKEN #REQUIRED
        size CDATA #IMPLIED
        input NMTOKEN #IMPLIED
        default CDATA #IMPLIED
        filter CDATA #IMPLIED
        readonly (true|false) "false"
        multiple (true|false) "false"
        required (true|false) "false"
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        hint CDATA #IMPLIED>

    <!ELEMENT validation EMPTY>
    <!ATTLIST validation
        rule NMTOKEN #REQUIRED
        value CDATA #IMPLIED>

    <!ELEMENT option (#PCDATA)+>
    <!ATTLIST option
        value CDATA #IMPLIED>

    <!ELEMENT case EMPTY>
    <!ATTLIST case
        field IDREF #REQUIRED
        value CDATA #REQUIRED
        use CDATA #REQUIRED>

    <!ELEMENT relations (belongsTo|belongsToMany|hasOne|hasMany|hasManyThrough)*>

    <!ELEMENT belongsTo EMPTY>
    <!ATTLIST belongsTo
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference IDREF #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT belongsToMany EMPTY>
    <!ATTLIST belongsToMany
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference IDREF #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasOne EMPTY>
    <!ATTLIST hasOne
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasMany EMPTY>
    <!ATTLIST hasMany
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasManyThrough EMPTY>
    <!ATTLIST hasManyThrough
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        joinTable NMTOKEN #REQUIRED
        joinRef NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

=== joomla-x/joomla-pythagoras/tests/unit/ORM/data/Detail.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Detail">

    <fields>
        <field name="id" type="id"/>
        <field name="field_1" type="text" default=""/>
        <field name="field_2" type="text" default=""/>
    </fields>

    <relations>
        <belongsTo
            name="master_id"
            entity="Master"
        />
        <hasOne
            name="extra"
            entity="Extra"
            reference="detail_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/tests/unit/ORM/data/Master.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Master">

    <fields>
        <field name="id" type="id"/>
        <field name="title" type="title"/>
        <field name="field_a" type="text" default=""/>
        <field name="field_b" type="text" default=""/>
        <field name="field_c" type="text" default=""/>
    </fields>

    <relations>
        <belongsTo
            name="parent_id"
            entity="Master"
        />
        <hasMany
            name="children"
            entity="Master"
            reference="parent_id"
        />
        <hasMany
            name="details"
            entity="Detail"
            reference="master_id"
        />
        <hasManyThrough
            name="tags"
            entity="Tag"
            reference="master_id"
            joinTable="map"
            joinRef="tag_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/libraries/incubator/PageBuilder/Entity/Template.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Template">

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="path" type="path"/>

        <field name="scripting" type="string"/>

    </fields>

    <relations>
        <hasMany name="masters"
                 entity="MasterLayout"
                 reference="template_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/libraries/incubator/Media/entities/Image.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\Media\Entity\Image">

    <storage>
        <default table="images"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>
        <field name="caption" type="string"/>
        <field name="description" type="string"/>
        <field name="url" type="string"/>
        <field name="creator" type="string"/>
        <field name="license" type="string"/>
        <field name="mime_type" type="string"/>
        <field name="width" type="integer"/>
        <field name="height" type="integer"/>
        <field name="exif" type="string"/>
    </fields>

</entity>

=== joomla-x/joomla-pythagoras/tests/unit/ORM/Mocks/Article.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\Tests\Unit\ORM\Mocks\Article">

    <storage>
        <default table="articles"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="teaser"
               type="richtext"
        />

        <field name="body"
               type="richtext"
        />

        <field name="author"
               type="text"
               default=""
        />

        <field name="license"
               type="text"
        >
            <validation rule="regex" value="copy(right|left)"/>
        </field>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="Article"
        />
        <hasMany name="children"
                 entity="Article"
                 reference="parent_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/extensions/Category/Entity/Category.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="article">

    <storage>
        <default table="category"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="body"
               type="richtext"
               label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
               description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
        />

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="category"
                   label="JFIELD_PARENT_LABEL"
                   description="JFIELD_PARENT_DESC"
        />
        <hasMany name="children"
                 entity="category"
                 reference="parent_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/tests/unit/ORM/Mocks/Tag.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\Tests\Unit\ORM\Mocks\Tag">

    <storage>
        <default table="tags"/>
    </storage>

    <fields>
        <field name="id" type="id"/>
        <field name="tag" type="text" default=""/>
        <field name="description" type="text" default=""/>
    </fields>

    <relations>
        <hasManyThrough
            name="masters"
            entity="Master"
            reference="tag_id"
            joinTable="map"
            joinRef="master_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/tests/unit/Content/data/article.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="article">

    <storage>
        <special dsn="csv://tests/unit/ORM/data/articles.csv"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="teaser"
               type="richtext"
        />

        <field name="body"
               type="richtext"
        />

        <field name="author"
               type="text"
               default=""
        />

        <field name="license"
               type="text"
        >
            <validation rule="regex" value="copy(right|left)"/>
        </field>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="article"
        />
        <hasMany name="children"
                 entity="article"
                 reference="parent_id"
        />
    </relations>

</entity>
