=== joomla-x/joomla-pythagoras/libraries/incubator/ORM/Definition/entity.dtd
<!ELEMENT entity ((storage)?, fields, (relations)?)>
    <!ATTLIST entity
        name CDATA #REQUIRED
        role (primary|lookup|map|inline|default) "default">

    <!ELEMENT storage (default|csv|api|special)>

    <!ELEMENT default EMPTY>
    <!ATTLIST default
        table NMTOKEN #REQUIRED>

    <!ELEMENT api EMPTY>
    <!ATTLIST api
        base-url CDATA #IMPLIED
        handler CDATA #REQUIRED>

    <!ELEMENT csv EMPTY>
    <!ATTLIST csv
        file CDATA #REQUIRED>

    <!ELEMENT special EMPTY>
    <!ATTLIST special
        dsn CDATA #REQUIRED>

    <!ELEMENT fields (field|fieldset)+>

    <!ELEMENT fieldset (field+|case+)>
    <!ATTLIST fieldset
        name ID #REQUIRED
        type NMTOKEN #REQUIRED
        entity CDATA #IMPLIED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT field (validation|option)*>
    <!ATTLIST field
        name ID #REQUIRED
        type NMTOKEN #REQUIRED
        size CDATA #IMPLIED
        input NMTOKEN #IMPLIED
        default CDATA #IMPLIED
        filter CDATA #IMPLIED
        readonly (true|false) "false"
        multiple (true|false) "false"
        required (true|false) "false"
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        hint CDATA #IMPLIED>

    <!ELEMENT validation EMPTY>
    <!ATTLIST validation
        rule NMTOKEN #REQUIRED
        value CDATA #IMPLIED>

    <!ELEMENT option (#PCDATA)+>
    <!ATTLIST option
        value CDATA #IMPLIED>

    <!ELEMENT case EMPTY>
    <!ATTLIST case
        field IDREF #REQUIRED
        value CDATA #REQUIRED
        use CDATA #REQUIRED>

    <!ELEMENT relations (belongsTo|belongsToMany|hasOne|hasMany|hasManyThrough)*>

    <!ELEMENT belongsTo EMPTY>
    <!ATTLIST belongsTo
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference IDREF #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT belongsToMany EMPTY>
    <!ATTLIST belongsToMany
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference IDREF #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasOne EMPTY>
    <!ATTLIST hasOne
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasMany EMPTY>
    <!ATTLIST hasMany
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

    <!ELEMENT hasManyThrough EMPTY>
    <!ATTLIST hasManyThrough
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        joinTable NMTOKEN #REQUIRED
        joinRef NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED>

=== joomla-x/joomla-pythagoras/libraries/incubator/PageBuilder/entities/Page.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\PageBuilder\Entity\Page">

    <storage>
        <default table="pages"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="url" type="url"/>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="page"
                   label="JFIELD_PARENT_LABEL"
                   description="JFIELD_PARENT_DESC"
        />
        <belongsTo name="master_id" entity="MasterLayout"/>
        <hasMany name="children" entity="Page" reference="parent_id"/>
        <hasMany name="content" entity="PageContent" reference="page_id"/>
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/extensions/Article/entities/Article.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\Extension\Article\Entity\Article">

    <storage>
        <default table="articles"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="alias"
               type="text"
               label="JGLOBAL_FIELD_ALIAS_LABEL"
               description="JGLOBAL_FIELD_ALIAS_DESC"
        />

        <field name="teaser"
               type="richtext"
               label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
               description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
        />

        <field name="body"
               type="richtext"
               label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
               description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
        />

        <field name="author"
               type="text"
               label="COM_CONTENT_FIELD_CREATED_BY_ALIAS_LABEL"
               description="COM_CONTENT_FIELD_CREATED_BY_ALIAS_DESC"
               default=""
        />

        <field name="license"
               type="text"
               label="JFIELD_META_RIGHTS_LABEL"
               description="JFIELD_META_RIGHTS_DESC"
        >
            <validation rule="regex" value="copy(right|left)"/>
        </field>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="Article"
                   label="JFIELD_PARENT_LABEL"
                   description="JFIELD_PARENT_DESC"
        />
        <hasMany name="children"
                 entity="Article"
                 reference="parent_id"
        />
    </relations>

</entity>

=== joomla-x/joomla-pythagoras/components/content/Entity/Article.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
	"/home/nibra/Development/nibralab/joomla-architecture/code/Joomla/ORM/Definition/entity.dtd">
<entity name="article">

	<storage>
		<csv file="components/content/data/articles.csv"/>
	</storage>

	<fields>
		<field name="id"
			   type="id"
			   label="JGLOBAL_FIELD_ID_LABEL"
			   description="JGLOBAL_FIELD_ID_DESC"
			   default="null"
		>
			<validation rule="positive"/>
			<validation rule="integer"/>
		</field>

		<field name="title"
			   type="title"
			   label="JGLOBAL_TITLE"
		>
			<validation rule="maxlen" value="64"/>
		</field>

		<field name="teaser"
			   type="richtext"
			   label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
			   description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
		/>

		<field name="body"
			   type="richtext"
			   label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
			   description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
		/>

		<field name="author"
			   type="text"
			   label="COM_CONTENT_FIELD_CREATED_BY_ALIAS_LABEL"
			   description="COM_CONTENT_FIELD_CREATED_BY_ALIAS_DESC"
			   default=""
		/>

		<field name="license"
			   type="text"
			   label="JFIELD_META_RIGHTS_LABEL"
			   description="JFIELD_META_RIGHTS_DESC"
		>
			<validation rule="regex" value="copy(right|left)"/>
		</field>

	</fields>

	<relations>
		<belongsTo name="parent_id"
				   entity="article"
				   label="JFIELD_PARENT_LABEL"
				   description="JFIELD_PARENT_DESC"
		/>
		<hasMany name="children"
				 entity="article"
				 reference="parent_id"
		/>
	</relations>

</entity>
